version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: hospital_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: HospitalManagement
      MYSQL_USER: hospital_user
      MYSQL_PASSWORD: hospital123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./make.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./test_data.sql:/docker-entrypoint-initdb.d/02-test-data.sql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - hospital_network

  adminer:
    image: adminer:latest
    container_name: hospital_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - hospital_network

  test_runner:
    image: mysql:8.0
    container_name: hospital_test
    depends_on:
      - mysql
    volumes:
      - ./test_queries.sql:/test_queries.sql
      - ./run_tests.sh:/run_tests.sh
    command: sh -c "chmod +x /run_tests.sh && /run_tests.sh"
    networks:
      - hospital_network

volumes:
  mysql_data:

networks:
  hospital_network:
    driver: bridge
