apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
data:
  hospital_management_system.sql: |-
    USE hospitaldb;
    
    -- 表一: 员工表（Employee）
    CREATE TABLE Employee (
        empNo CHAR(5) PRIMARY KEY COMMENT '员工工号',
        empName VARCHAR(10) NOT NULL COMMENT '姓名',
        empStatus VARCHAR(5) COMMENT '在职状态',
        empDutyStatus VARCHAR(5) COMMENT '在岗状态',
        empEntryYear DATE COMMENT '入职年份',
        empJobPosition CHAR(4) COMMENT '职级',
        empProfile TEXT COMMENT '个人简介'
    );
    
    -- 表二: 人事管理员表（PersonnelAdministrator）
    CREATE TABLE PersonnelAdministrator (
        paNo CHAR(5) PRIMARY KEY COMMENT '人事管理员工号',
        CONSTRAINT fk_personnelAdmin_employee FOREIGN KEY (paNo) REFERENCES Employee(empNo)
    );
    
    -- 表三: 人员管理（Manage）
    CREATE TABLE Manage (
        paNo CHAR(5) COMMENT '人事管理员工号',
        empNo CHAR(5) COMMENT '员工工号',
        PRIMARY KEY (paNo, empNo),
        CONSTRAINT fk_manage_pa FOREIGN KEY (paNo) REFERENCES PersonnelAdministrator(paNo),
        CONSTRAINT fk_manage_emp FOREIGN KEY (empNo) REFERENCES Employee(empNo)
    );
